package PersonaApp;


/**
* PersonaApp/PersonaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Persona.idl
* lunes 23 de abril de 2018 07:37:35 PM COT
*/

public interface PersonaOperations 
{
  boolean insertarPersona (int id_persona, String nombre, String apellido, int telefono, String direccion, String correo);
  String consultarPersona (int id_persona);
  boolean eliminarPersona (int id_persona);
  boolean actualizarPersona (int id_persona, String nombre, String apellido, int telefono, String direccion, String correo);
  String listarPersonas ();
  void shutdown ();
} // interface PersonaOperations
